# -*- coding: utf-8 -*-
"""user_research_concept_maps.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13DsFqzxY2QsoI6Pv3_M_xDj0p79Q7Ahq
"""

import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.cm import get_cmap
from matplotlib.colors import to_rgba, to_hex
from itertools import cycle
from google.colab import files


def lighten_color(color, fraction=0.3):
    rgba_color = to_rgba(color)
    lighter_color = ((1 - fraction) * rgba_color[i] + fraction for i in range(3))
    return to_hex((*lighter_color, 1))

def grouped_concentric_radial_layout(G, core_node, main_themes, sub_themes):
    pos = {}
    pos[core_node] = (0, 0)
    num_main_themes = len(main_themes)
    main_radius = 2
    for i, theme in enumerate(main_themes):
        angle = 2 * np.pi * i / num_main_themes
        pos[theme] = (main_radius * np.cos(angle), main_radius * np.sin(angle))
        num_sub_themes = len(sub_themes[theme])
        sub_radius = 1.5
        sub_angle_start = angle - (np.pi / (num_main_themes * 1.5))
        sub_angle_end = angle + (np.pi / (num_main_themes * 1.5))
        for j, subtheme in enumerate(sub_themes[theme]):
            sub_angle = sub_angle_start + (sub_angle_end - sub_angle_start) * j / (num_sub_themes - 1 if num_sub_themes > 1 else 1)
            pos[subtheme] = ((main_radius + sub_radius) * np.cos(sub_angle),
                             (main_radius + sub_radius) * np.sin(sub_angle))
    return pos


# Custom color sequence (excluding red)
custom_colors = cycle([
    '#6a3d9a', '#a6cee3', '#1f78b4', '#b2df8a',
    '#33a02c', '#cab2d6', '#fdbf6f', '#ff7f00',
])

def paired_colors(index):
    return next(custom_colors)

def draw_final_concept_map(G, pos, core_node, main_themes, sub_themes):
    plt.figure(figsize=(12, 8))  # Removed facecolor='whitesmoke'
    core_color = paired_colors(1)
    nx.draw_networkx_nodes(G, pos, nodelist=[core_node], node_size=5000, node_color=[core_color], node_shape='o')
    nx.draw_networkx_labels(G, pos, labels={core_node: core_node}, font_size=12, font_weight='bold')

    for i, theme in enumerate(main_themes):
        theme_color = paired_colors(i + 2)
        subtheme_colors = [lighten_color(theme_color) for _ in sub_themes[theme]]
        nx.draw_networkx_nodes(G, pos, nodelist=[theme], node_size=3000, node_color=[theme_color], node_shape='o')
        nx.draw_networkx_nodes(G, pos, nodelist=sub_themes[theme], node_size=2000, node_color=subtheme_colors, node_shape='o')
        nx.draw_networkx_labels(G, pos, labels={node: node for node in [theme] + sub_themes[theme]}, font_size=8)

    nx.draw_networkx_edges(G, pos, edge_color='gray', width=1, arrowsize=15)
    plt.title("Decison-maker 9: Concept Map", fontsize=24, pad=20)
    plt.axis("off")
    plt.tight_layout()
    plt.show()
    plt.savefig("Decison-maker 9: Concept Map.png")


# Main themes and sub-themes
main_themes = ["Data", "Strategy", "Evidence", "Question", "Trust", "System"]
sub_themes = {
    "Data": ["Accuracy", "Repeatability", "Visualisation", "Reliability"],
    "Strategy": ["Logic", "Context", "Assumptions", "Framework", "Advantage"],
    "Evidence": ["Assessment", "Corroboration", "Evaluation", "Prediction", "War-gaming"],
    "Question": ["Problem", "Challenges", "Conversation", "Hypothesis"],
    "Trust": ["Confidence-levels", "Transparency", "Falsifiability", "Effectiveness", "Objectivity"],
    "System": ["Departments", "Minister", "Intelligence", "Integrated", "Team"]
}

# Create the graph and add nodes and edges
G_updated = nx.DiGraph()
G_updated.add_node("Data-Driven Decision Making")
G_updated.add_nodes_from(main_themes)
G_updated.add_edges_from([("Data-Driven Decision Making", theme) for theme in main_themes])
for theme, subtheme_list in sub_themes.items():
    G_updated.add_nodes_from(subtheme_list)
    G_updated.add_edges_from([(theme, subtheme) for subtheme in subtheme_list])

# Compute the grouped concentric radial layout positions
grouped_concentric_radial_positions_final = grouped_concentric_radial_layout(G_updated, "Data-Driven Decision Making", main_themes, sub_themes)

# Draw the final concept map
draw_final_concept_map(G_updated, grouped_concentric_radial_positions_final, "Data-Driven Decision Making", main_themes, sub_themes)

# Download image
files.download('Decison-maker 9: Concept Map.png')

"""#Decision-maker"""

# Decision-maker 1: # Main themes and sub-themes
main_themes = ["Data", "Signal", "Time", "Communication", "Trust"]
sub_themes = {
    "Data": ["Processing", "Repeatable", "Robust", "Forcast", "Metadata"],
    "Signal": ["Sampling", "Frequency", "Sensors", "Signatures", "Sonar"],
    "Time": ["Mission", "Outcomes", "Standards", "Strategic", "Tactical"],
    "Communication": ["Judgement", "Context", "Assumptions", "Listening", "Visualisation"],
    "Trust": ["Importance", "Source", "Expertise", "Experience", "Truth"]
}

# Decision-maker 2: # Main themes and sub-themes
main_themes = ["Data", "Confidence", "Time", "Importance", "Trust", "Decisions"]
sub_themes = {
    "Data": ["Process", "Availability", "Source", "Accuracy", "Patterns"],
    "Confidence": ["Utility", "Context", "Judgement", "Experience", "Independence"],
    "Time": ["Crisis", "Commercial", "Modelling", "Triage", "History"],
    "Importance": ["Problem", "Challenges", "Politics", "Responsibility", "Levels"],
    "Trust": ["Collective", "Evidence", "Reliability", "Limitations", "Motivations"],
    "Decisions": ["Intelligence", "People", "Teaming", "Language", "Departments", "Subjectivity"]
}

# Decision-maker 3: # Main themes and sub-themes
main_themes = ["Data", "Method", "Time", "Communication", "Trust", "People"]
sub_themes = {
    "Data": ["Representative", "Limitations", "Provenance", "Distribution", "Insights"],
    "Method": ["Visualisation", "Models", "Experiments", "Sensing", "Speed"],
    "Time": ["Future", "Strategic", "Tactical", "Change", "History"],
    "Communication": ["Levels", "Importance", "Awareness", "Format"],
    "Trust": ["Impact", "Certainty", "Classification", "Authority", "Performance"],
    "People": ["Learning", "Interest", "Stakeholders", "Government", "Expertise"]
}

# Decision-maker 4: # Main themes and sub-themes
main_themes = ["Data", "Policy", "People", "Time", "Trust", "Communication"]
sub_themes = {
    "Data": ["Methodology", "Qualitative vs. Quantitative", "Reliability", "Appropriateness"],
    "Policy": ["Specificity", "Need", "Tactical", "Integrated", "Assessment"],
    "People": ["Question", "Conversations", "Judgement", "Relationships", "Expertise"],
    "Time": ["Change", "Collection", "Forcasts", "Situation", "Geography"],
    "Trust": ["Source", "Motivation", "Evidence", "Confidence-levels", "Triangulated"],
    "Communication": ["Response", "Context", "Visualisation", "Subjectivity", "Story-telling"]
}

# Decision-maker 5: # Main themes and sub-themes
main_themes = ["Data", "Need", "Time", "Communication", "Trust", "System"]
sub_themes = {
    "Data": ["Threshold", "Representation", "Collection", "Ethics", "Challenges"],
    "Need": ["Significance", "Policy", "Evidence", "Specificity", "Questions", "Benefits"],
    "Time": ["Time Period", "Snapshot", "Change", "History", "Retrospective"],
    "Communication": ["Context", "Visualisation", "Imaging", "Consious vs. Unconsious"],
    "Trust": ["Confidence", "Bias", "Context", "Source", "Responsibility"],
    "System": ["Requirements", "Digital", "Intelligence", "Capabilities", "Procedures"]
}

# Decision-maker 6: # Main themes and sub-themes
main_themes = ["Data", "Decision", "Time", "Communication", "Trust"]
sub_themes = {
    "Data": ["Collection", "Storage", "Fidelity", "Certainty", "Utility"],
    "Decision": ["Judgement", "Complexity", "Power", "Experience", "Programmatic"],
    "Time": ["Time Period", "Frequency", "Probability", "Originality", "Difficult"],
    "Communication": ["Explaination", "Interpretation", "Presentation", "Visualisation", "Dashboard"],
    "Trust": ["Risk", "Guarantees", "Expertise", "Sources", "Classification"],
}

# Decision-maker 7: # Main themes and sub-themes
main_themes = ["Data", "Need", "Time", "Communication", "Trust", "Understanding"]
sub_themes = {
    "Data": ["Analysis", "Quality", "Underlying Patterns", "Collection", "Comparison"],
    "Need": ["Issue", "Intelligence", "Policy", "Sufficiency", "Framework"],
    "Time": ["Change", "Tactical", "Reactive", "Negotiation", "Challenging"],
    "Communication": ["Visualisation", "Ministers", "Context", "Interrogatable", "Metrics"],
    "Trust": ["Confidence", "Impact", "Judgement", "Advice", "Verification"],
    "Understanding": ["Support", "Level", "Responsibility", "Oversight", "Tools & Capabilities"]
}

# Decision-maker 8: # Main themes and sub-themes
main_themes = ["Data", "People", "Time", "Communication", "Trust", "Decision"]
sub_themes = {
    "Data": ["Errors", "Rigor", "Models", "Correlation", "Pipeline"],
    "People": ["Scientific", "Seniors", "Practitioners", "Departments", "Trainity"],
    "Time": ["Chance", "Uncertainty", "Relativity", "Future", "Specificity"],
    "Communication": ["Visualisation", "Explaination", "Engagement", "Objectivity", "Audience"],
    "Trust": ["Confidence", "Source", "Limitations", "Sensibility", "Thresholds"],
    "Decision": ["Question", "Level", "Comfort", "Commision & Funding", "Significance"]
}

# Decision-maker 9: # Main themes and sub-themes
main_themes = ["Data", "Strategy", "Evidence", "Question", "Trust", "System"]
sub_themes = {
    "Data": ["Accuracy", "Repeatability", "Visualisation", "Reliability"],
    "Strategy": ["Logic", "Context", "Assumptions", "Framework", "Advantage"],
    "Evidence": ["Assessment", "Corroboration", "Evaluation", "Prediction", "War-gaming"],
    "Question": ["Problem", "Challenges", "Conversation", "Hypothesis"],
    "Trust": ["Confidence-levels", "Transparency", "Falsifiability", "Effectiveness", "Objectivity"],
    "System": ["Departments", "Minister", "Intelligence", "Integrated", "Team"]
}

"""#Data Practitioner"""

# Data pracitioner 1: # Main themes and sub-themes
main_themes = ["Data", "Subjectivity", "Time", "Decisions", "Exploration", "Trust"]
sub_themes = {
    "Data": ["Bias", "Method", "Samples", "Models", "Nuance"],
    "Subjectivity": ["Experience", "Policy", "Motivation", "Definitions", "Truth"],
    "Time": ["Future", "Intervals or  Stages", "Estimates", "Progression"],
    "Decisions": ["Communication", "Visualisation", "Strategic", "Uncertainty", "Assurance"],
    "Exploration": ["Looking", "Trying", "Questions", "Perspectives", "Searching"],
    "Trust": ["Source", "Confidence", "Limitations", "Context"]
}

# Data pracitioner 2: # Main themes and sub-themes
main_themes = ["Data", "Domain", "Time & Space", "Trust", "Communication", "Decisions"]
sub_themes = {
    "Data": ["Analysis Pipeline", "Distributions", "Models", "Correlations", "Changes"],
    "Domain": ["Quantum", "Mechaniscs", "Space", "Frequency", "Perspectives"],
    "Time & Space": ["Time Period", "Fluctuations", "Need"],
    "Trust": ["Assumptions", "Process", "Honesty", "Exactness", "Confidence"],
    "Communication": ["Conversation", "Audience", "Visualisation", "Deomstrate", "Context"],
    "Decisions": ["Questions", "Choices", "Prediction", "Level", "Importance"]
}

# Data pracitioner 3: # Main themes and sub-themes
main_themes = ["Data", "Time", "Communication", "People", "Trust"]
sub_themes = {
    "Data": ["Analysis", "Collection", "Models", "Patterns", "Uncertainty"],
    "Time": ["Computation", "Frequency", "Temproal", "Future", "Differences"],
    "Communication": ["Visualisation", "Engagement", "Design", "Challenges", "Purpose"],
    "People": ["Stakeholders", "Awareness", "Understanding", "Level", "Experience"],
    "Trust": ["Method", "Importance", "Confidence", "Uncertainty", "Value"]
}

# Data pracitioner 4: # Main themes and sub-themes
main_themes = ["Data", "Time", "Decisions", "Trust", "Communication"]
sub_themes = {
    "Data": ["Forcasts", "Modelling", "Sense", "Provenance", "Comparison"],
    "Time": ["Change", "Time Period", "Frequency", "Future", "Past"],
    "Decisions": ["Impact", "Comfort", "Dependencies", "Complexity", "Comparison"],
    "Trust": ["Considerations", "Confidence", "Performance", "Relability"],
    "Communication": ["Certainty", "Visualisation", "Video", "Context", "Interest"]
}

# Data pracitioner 5: # Main themes and sub-themes
main_themes = ["Data", "Understanding", "People", "Time", "Trust", "Communication"]
sub_themes = {
    "Data": ["Process", "Utility", "Provenance", "Statistics", "Metrics"],
    "Understanding": ["Question", "Policy", "Implications", "subtleties"],
    "People": ["Need", "Experience", "Convincing", "Department", "Team"],
    "Time": ["Time Period", "Change", "Space", "Specifity", "Latest"],
    "Trust": ["Confidence", "Risks", "Assumptions", "Security", "Dilligence", "Certainty"],
    "Communication": ["Limitations", "Visualisation", "Story", "Interpretations", "Difficult"]
}

# Data pracitioner 6: # Main themes and sub-themes
main_themes = ["Data", "Knowledge", "Communication", "Decisions", "Trust", "Method"]
sub_themes = {
    "Data": ["Process", "Models", "Algorithms", "Sampling", "Provenance"],
    "Knowledge": ["Advice", "Understanding", "Fact", "Uncertainity", "Probability", "Learning"],
    "Communication": ["Visualisation", "Language", "Conversations", "Terms", "Intent"],
    "Decisions": ["Question", "Classification", "Management", "Policy", "Implications"],
    "Trust": ["Limitations", "Confidence", "Assumpptions", "Representativeness"],
    "Method": ["Signals", "Sensors", "Tracking", "System", "Manipulable"]
}

# Data pracitioner 7: # Main themes and sub-themes
main_themes = ["Data", "Time", "Decision", "Understanding", "Communication", "Trust"]
sub_themes = {
    "Data": ["Collection", "Pipeline", "Process", "Quality", "Auditable"],
    "Time": ["Change", "Practicalities", "Hindsight", "Technology", "Moment"],
    "Decision": ["Question", "Need", "Context", "Role", "Outcomes", "Empowered"],
    "Understanding": ["Backgeround", "Experience", "Research", "Dependencies", "Doctrines"],
    "Communication": ["Visualisation", "Discussion", "Interaction", "Interest", "Intention"],
    "Trust": ["Reproducibility", "Explainable", "Challenges", "Justifiable", "Judgement"]
}