source("D:/Morgan/Documents/NCL MSc/final_project/mofrod_project/munge/01-A.R", echo=TRUE)
source("D:/Morgan/Documents/NCL MSc/final_project/mofrod_project/src/all_downsampling_functions.R", echo=TRUE)
source("D:/Morgan/Documents/NCL MSc/final_project/mofrod_project/src/annotatedchange_downsampling_experiments.R", echo=TRUE)
source("D:/Morgan/Documents/NCL MSc/final_project/mofrod_project/src/annotatedchange_apply_original_catch22.R", echo=TRUE)
source("D:/Morgan/Documents/NCL MSc/final_project/mofrod_project/src/annotatedchange_apply_imputeTS_catch22.R", echo=TRUE)
source("D:/Morgan/Documents/NCL MSc/final_project/mofrod_project/src/annotatedchange_process_3.R", echo=TRUE)
